Validate contact form
Rn486/Recillah-Khamala-Portfolio pull request #10
Opened 2022-07-23 20:53 UTC by Rn486

For this pull request,

- I used JavaScript to ensure that emails submitted to the form are valid and the invalid information is not submitted.
- I also used CSS to style the changes and required HTML changes to make this possible.

2022-07-23 21:24 UTC, 1GORDON requested changes
##
## Hi @Rn486 & @elfin-git  ✋

Good job so far!

## Highlights!
- Followed Gitflow ✔️ 
- Good commit messages ✔️
- Descriptive Pull request ✔️
- Professional readme ✔️

Hello ✋, you have done well reaching this point of the milestone 🤝 . But there are some issues that you still need to work on to go to the next project but you are almost there!

# Status: Required Changes ♻️⛔️

- [ ] ⛔️ Kindly make sure your `linters` are passing. At the moment your `ESLint` is failing. It is hard to have a project approved when the `linters` are failing.

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread and tag me `@1GORDON` if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-23 21:24 UTC, 1GORDON commented on js/pwindow.js
> +
Great job team 🤝

- [ ] It is regarded as a bad practice according to the [Javascript good practices](https://github.com/microverseinc/curriculum-html-css/blob/main/articles/javascript_best_practices.md) to leave commented code in your project. Kindly remove commented and unused code from your javascript files.

2022-07-23 21:24 UTC, 1GORDON commented on index.html
> +            <!-- <div class="single-card card1 ">
Great job team 🤝

- [ ] Kindly remove commented code from your HTML file. This is not regarded as a good practice.

2022-07-23 21:24 UTC, 1GORDON commented on index.html
> +                    <form noValidate action="https://formspree.io/f/mgedjkyb" id="form1" method="post" class="contact-form">
Great job team 🤝

- [ ] As specified in the project requirements, your form is supposed to submit if the validation is okay. Unfortunately, your form is not submitted even when the email is lowercase. Kindly make sure your form is submitted properly to `form spree`.

2022-07-23 21:24 UTC, 1GORDON commented on index.html
>                                  required></textarea>
Great design team 🤝

- [ ] [Optional] You may kindly make your text area similar to the design provided in the Figma template.
- Your design
![form](https://user-images.githubusercontent.com/63917725/180623238-eca0ba3a-c419-4fe8-84ee-03c5174ff210.PNG)

- Figma design
![Figma](https://user-images.githubusercontent.com/63917725/180623291-9a63ba11-fe6b-43ba-9a86-1924ae891356.PNG)

2022-07-25 07:17 UTC, KayLemba approved these changes
# STATUS: APPROVED :green_circle: :clap: 

Hello  @Rn486    , 
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

HIGHLIGHTS:

- Your project is professional 
- Your repo is professional 
- Well structured files 


Now you can merge this branch and move on :1st_place_medal: 
HAPPY CODING AND GOOD LUCK WITH THE COMMING ONES :crossed_fingers: :four_leaf_clover: 

![well-1](https://user-images.githubusercontent.com/64173189/128382030-38e7de91-f6f2-45cf-b54e-8068e0446e4c.gif)

[OPTIONAL] Kindly add a screenshot to your README file showing your webpage user Interface. You can use extentions like fireshot to capturer the entire page.

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-25 07:38 UTC, merged